const user = {
    handle: 'Something',
    email: 'mail@mail.com',
    createdAt: '2022-01-2022-01-23T17:12:22.474Z',
    imgURL: '/user/img/1010101019293.png',
    userId: 'GHajidaijsdoj1383082',
    fullName: 'Tim McMacken',
    jobTitle: 'Engineer',
    affiliation: 'Independent',
    currentLocation: 'Oakland CA USA',
    isLatinX: 'No',
    bio: 'Engineer, biker, baker, nerd!',
    website: 'timmcmacken.com',
    publicProfile: 'No'
}

const mentee = {
    createdAt: '2022-01-2022-01-23T17:12:22.474Z',
    email: 'tim@nopemail.com',
    fullName: 'Tim McMacken',
    gender: 'Male',
    isLatinX: 'No',
    countryOrigin: 'USA',
    currentLocation: 'Oakland CA USA',
    affiliation: 'Holberton School',
    position: 'Early Career',
    scholarOrWebsite: 'http://www.googlescholar.com',
    languages: ['English'],
    timezone: 'UTC-8',
    mentorshipArea: ['Strengthening skills (Writing or Communication or Engineering)',
                    'Research Guidance (AI Verticals)',
                    'Career Guidance (New Degree or Job or Promotion)'],
    motivationStatement: 'I want to be an AI engineer',
    prefferedOutcomes: [
        'Connect to job/research opportunities',
        'Establish a research partnership', 
        'Connect to scholarships/graduate opportunities',
        'Improve technical and soft skills in general'],
    discussAfter: 'Yes',
    careerGoals: 'I want to be an AI engineer at a MANGA company',
    skillMentorship: ['Verbal Communication',
                        'Writing', 
                        'Finding papers related to my area', 
                        'Engineering'],
    researchAreas: ['Probabilistic Inference / Bayesian Methods / Graphical Models / Causality', 
                    'Representation Learning / Unsupervised Feature Learning',
                    'Generative Models'],
    careerAdvice: ['Advice on applications and interviews',
                    'Connect to scholarships',
                    'Connect to job/research opportunities'],
    workshopReviewer: '2',
    peerReviewedPubs: 'Yes',
    topTierReviewer: 'No',
    topTierPub: 'No',
    highImpactReviewer: 'No',
    peerReviewedHighImpact: 'No',
    conferencePreference: ['CVPR (IEEE Conference on Computer Vision)',
                            'NAACL (The North American Chapter of the Association for Computational Linguistics)',
                            'ICML (International Conference on Machine Learning)', 
                            'NeurIPS (Neural Information Processing Systems)'],
    otherConferences: 'SSSS (Super Secret Skynet Symposium), Holberton Demoday',
    handle: 'TMcMac',
    userId: '098ad0ausf09q8f09aui'
}

const mentor = {
    date: '2022-01-2022-01-23T17:12:22.474Z',
    email: 'tim@nopemail.com',
    name: 'Tim McMacken',
    gender: 'Male',
    isLatinX: 'No',
    countryOrigin: 'USA',
    currentLocation: 'Oakland CA USA',
    affiliation: 'Holberton School',
    position: 'Post Doc',
    scholarOrWebsite: 'http://www.googlescholar.com',
    languages: ['English', 'Spanish', 'French'],
    timezone: 'UTC-8',
    mentoredPreviously: 'Yes, with another organization',
    mentorshipArea: ['Strengthening skills (Writing or Communication or Engineering)',
                    'Research Guidance (AI Verticals)',
                    'Career Guidance (New Degree or Job or Promotion)'],
    hoursAvailable: '2',
    menteePref: ['Early Career Industry Professional',
                'Ph.D. or Post-Doc'],
    otherMenteePref: 'I want to work with someone eager to learn',
    prefferedOutcomes: ['Improve your experience and career level by mentoring others',
                        'Establish a research collaboration', 
                        'Co-author research with a mentee',
                        'Hire entry-level candidates'],
    discussAfter: 'Yes',
    careerGoals: 'I want to be an AI engineer at a MANGA company',
    skillMentorship: ['Verbal Communication',
                        'Writing', 
                        'Finding papers related to my area', 
                        'Engineering'],
    researchAreas: ['Probabilistic Inference / Bayesian Methods / Graphical Models / Causality', 
                    'Representation Learning / Unsupervised Feature Learning',
                    'Generative Models'],
    careerAdvice: ['Advice on applications and interviews',
                    'Connect to scholarships',
                    'Connect to job/research opportunities'],
    workshopReviewer: '2',
    peerReviewedPubs: 'Yes',
    topTierReviewer: 'No',
    topTierPub: 'No',
    highImpactReviewer: 'No',
    peerReviewedHighImpact: 'No',
    conferencePreference: ['CVPR (IEEE Conference on Computer Vision)',
                            'NAACL (The North American Chapter of the Association for Computational Linguistics)',
                            'ICML (International Conference on Machine Learning)', 
                            'NeurIPS (Neural Information Processing Systems)'],
    otherConferences: 'SSSS (Super Secret Skynet Symposium), Holberton Demoday',
    handle: 'TMcMac',
    userId: '098ad0ausf09q8f09aui'
}